const nodemailer = require('nodemailer');
const mailer = nodemailer.createTransport({
    service:'gmail',
    host:'smtp.gmail.com',
    port:587,
    secure:false,
    auth:{
        user: process.env.SMTP_USER,
        pass: process.env.SMTP_PASS
    }
})

async function sendBusinessVerificationMail(mailData){
    const mailOptions = {
        from: process.env.SMTP_USER,
        to: mailData.email,
        subject:'Verify your business account',
        text:`Hi ${mailData.name || ''},\n\nPlease confirm your account by clicking the link below:\n\n${mailData.verificationLink}\n\nThis link expires in ${mailData.expiryHours} hours.\n\nIf you didn't request this, ignore this email.`,
        html: `<p>Hi ${mailData.name || ''},</p>
        <p>Please confirm your account by clicking the link below:</p>
        <p><a href="${mailData.verificationLink}">Confirm my account</a></p>
        <p>This link expires in ${mailData.expiryHours} hours.</p>`
    }
    try{
        await mailer.sendMail(mailOptions);
        return true;
    }
    catch(error){
        console.error('send-verification error',error);
        return false;
    }
}

async function sendBookingDetailsMail(mailData){
  const businessHtml = `
  <div style="margin:0;padding:0;background:#f8fafc;font-family:'Plus Jakarta Sans',-apple-system,BlinkMacSystemFont,'Segoe UI',Arial,sans-serif;">
    <div style="max-width:520px;margin:24px auto;padding:20px;background:#ffffff;border-radius:12px;border:1px solid #e5e7eb;box-shadow:0 6px 22px rgba(15,23,42,0.06);">
      
      <!-- Brand header -->
      <div style="display:flex;align-items:center;justify-content:space-between;margin-bottom:16px;">
        <div style="display:flex;align-items:center;gap:8px;">
          <div style="width:32px;height:32px;border-radius:999px;background:linear-gradient(135deg,#5d00ff,#7b2eff);display:flex;align-items:center;justify-content:center;color:#ffffff;font-size:16px;font-weight:700;">
            B
          </div>
          <div>
            <div style="font-size:16px;font-weight:600;color:#0f172a;">BookLeaf</div>
            <div style="font-size:12px;color:#6b7280;">New booking received</div>
          </div>
        </div>
        <span style="font-size:12px;color:#9ca3af;">${new Date().toLocaleString()}</span>
      </div>

      <h2 style="font-size:18px;margin:0 0 12px;color:#0f172a;">New Booking Received</h2>
      <p style="margin:0 0 16px;color:#4b5563;font-size:14px;">
        You’ve received a new booking via your BookMate page.
      </p>

      <!-- Booking details -->
      <div style="border-radius:10px;border:1px solid #e5e7eb;background:#f9fafb;padding:12px 14px;margin-bottom:16px;">
        <div style="margin-bottom:8px;">
          <span style="font-size:12px;color:#6b7280;text-transform:uppercase;letter-spacing:0.04em;font-weight:600;">Customer</span>
        </div>
        <p style="margin:0 0 4px;font-size:14px;color:#0f172a;"><strong>Name:</strong> ${mailData.customer_name}</p>
        <p style="margin:0 0 4px;font-size:14px;color:#0f172a;"><strong>Email:</strong> ${mailData.customer_email}</p>
        <p style="margin:0 0 4px;font-size:14px;color:#0f172a;"><strong>Phone:</strong> ${mailData.customer_phone}</p>
      </div>

      <div style="border-radius:10px;border:1px solid #e5e7eb;background:#f9fafb;padding:12px 14px;margin-bottom:16px;">
        <div style="margin-bottom:8px;">
          <span style="font-size:12px;color:#6b7280;text-transform:uppercase;letter-spacing:0.04em;font-weight:600;">Appointment</span>
        </div>
        <p style="margin:0 0 4px;font-size:14px;color:#0f172a;"><strong>Date:</strong> ${mailData.booked_date}</p>
        <p style="margin:0;font-size:14px;color:#0f172a;"><strong>Time:</strong> ${mailData.booked_time}</p>
      </div>

      <div style="border-radius:10px;border:1px dashed #e5e7eb;background:#fefce8;padding:12px 14px;margin-bottom:20px;">
        <p style="margin:0 0 4px;font-size:13px;color:#4b5563;font-weight:600;">Customer message</p>
        <p style="margin:0;font-size:13px;color:#4b5563;">
          ${mailData.message || "No message was provided for this booking."}
        </p>
      </div>

      <p style="margin:0 0 4px;font-size:12px;color:#9ca3af;">
        This email was automatically generated by <strong>BookMate</strong>.
      </p>
      <p style="margin:0;font-size:12px;color:#9ca3af;">
        You can reply directly to this email to contact the customer.
      </p>
    </div>
  </div>
`;

const businessMail = {
  from: process.env.SMTP_USER,
  to: mailData.business_email,
  subject: "New Booking via BookLeaf",
  html: businessHtml,
};

const customerHtml = `
  <div style="margin:0;padding:0;background:#f8fafc;font-family:'Plus Jakarta Sans',-apple-system,BlinkMacSystemFont,'Segoe UI',Arial,sans-serif;">
    <div style="max-width:520px;margin:24px auto;padding:20px;background:#ffffff;border-radius:12px;border:1px solid #e5e7eb;box-shadow:0 6px 22px rgba(15,23,42,0.06);">
      
      <!-- Brand header -->
      <div style="display:flex;align-items:center;gap:8px;margin-bottom:16px;">
        <div style="width:32px;height:32px;border-radius:999px;background:linear-gradient(135deg,#5d00ff,#7b2eff);display:flex;align-items:center;justify-content:center;color:#ffffff;font-size:16px;font-weight:700;">
          B
        </div>
        <div>
          <div style="font-size:16px;font-weight:600;color:#0f172a;">BookLeaf</div>
          <div style="font-size:12px;color:#6b7280;">Your booking has been received</div>
        </div>
      </div>

      <h2 style="font-size:18px;margin:0 0 10px;color:#0f172a;">We’ve received your booking</h2>

      <p style="margin:0 0 10px;font-size:14px;color:#4b5563;">
        Hi <strong>${mailData.customer_name}</strong>,
      </p>

      <p style="margin:0 0 16px;font-size:14px;color:#4b5563;">
        Thank you for booking an appointment with <strong>${mailData.business_name}</strong>.
        Here are your booking details:
      </p>

      <div style="border-radius:10px;border:1px solid #e5e7eb;background:#f9fafb;padding:12px 14px;margin-bottom:16px;">
        <p style="margin:0 0 4px;font-size:14px;color:#0f172a;">
          <strong>Date:</strong> ${mailData.booked_date}
        </p>
        <p style="margin:0 0 4px;font-size:14px;color:#0f172a;">
          <strong>Start Time:</strong> ${mailData.start_at}
        </p>
        <p style="margin:0;font-size:14px;color:#0f172a;">
          <strong>End Time:</strong> ${mailData.end_at}
        </p>
      </div>

      <p style="margin:0 0 10px;font-size:14px;color:#4b5563;">
        If you need to change or cancel your booking, please contact
        <strong>${mailData.business_name}</strong> directly.
      </p>

      <p style="margin:0 0 18px;font-size:14px;color:#4b5563;">
        We’ll let you know if anything changes.
      </p>

      <p style="margin:0 0 4px;font-size:12px;color:#9ca3af;">
        Thank you for choosing <strong>${mailData.business_name}</strong>.
      </p>
      <p style="margin:0;font-size:12px;color:#9ca3af;">
        Powered by <strong>BookMate</strong>.
      </p>
    </div>
  </div>
`;

const customerMail = {
  from: process.env.SMTP_USER,
  to: mailData.customer_email,
  subject: "Your booking has been received – BookMate",
  html: customerHtml,
};


    try{
        await mailer.sendMail(businessMail);
        await mailer.sendMail(customerMail);
        return true;
    }   
    catch(error){
        console.error('mail failed');
        return false;
    } 

}

module.exports = {sendBusinessVerificationMail,sendBookingDetailsMail}